name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 New Features'
    label: 'new feature'
  - title: '🔬 Improvements'
    label: 'enhancement'
  - title: '🐞 Bug Fixes'
    label: 'bug'
  - title: '📦 Dependency updates'
    label: 'dependencies'
  - title: '📄 Documentation updates'
    label: 'documentation'

change-template: '* $TITLE (via #$NUMBER) - @$AUTHOR'
template: |
  $CHANGES
  ## 👀 Links
  [Commits since $PREVIOUS_TAG](https://github.com/andrcuns/addon-storyshots-wdio/compare/$PREVIOUS_TAG...master)
