language: node_js
node_js:
  - "12"

cache: yarn

script: yarn lint && yarn test
before_deploy:
  - yarn build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: "$NPM_TOKEN"
  on:
    tags: true
    skip_cleanup: true
