name: Publish

on:
  push:
    tags:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish
        run: |
          yarn install
          yarn build
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
